In [2]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Original Matrix:")
for row in matrix:
    print(row)


rows = len(matrix)
cols = len(matrix[0])
if rows == cols:
    print("\nThis is a square matrix.")
else:
    print("\nThis is NOT a square matrix.")    

Original Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

This is a square matrix.


In [ ]:
import numpy as np
diagonal_elements = [5, 8, 3]

diagonal_matrix = np.diag(diagonal_elements)

print("Diagonal Matrix:")
for row in diagonal_matrix:
    print(row)
    


Diagonal Matrix:
[5 0 0]
[0 8 0]
[0 0 3]


In [8]:
identity_matrix = np.identity(3, dtype=int)
print("Identity Matrix:")
print(identity_matrix)

full_matrix = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])


lower_triangle = np.tril(full_matrix)
print("\nLower Triangular Matrix:")
print(lower_triangle)

upper_triangle = np.triu(full_matrix)
print("\nUpper Triangular Matrix:")
print(upper_triangle)


A = np.random.randint(1, 10, size=(3, 3))
symmetric_matrix = (A + A.T) // 2
print("Original Matrix A:")
print(A)

print("\nSymmetric Matrix:")
print(symmetric_matrix)

# Check if matrix equals its transpose
is_symmetric = np.array_equal(symmetric_matrix, symmetric_matrix.T)
print("\nIs symmetric:", is_symmetric)



Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Lower Triangular Matrix:
[[1 0 0]
 [4 5 0]
 [7 8 9]]

Upper Triangular Matrix:
[[1 2 3]
 [0 5 6]
 [0 0 9]]
Original Matrix A:
[[7 9 5]
 [4 1 2]
 [7 7 7]]

Symmetric Matrix:
[[7 6 6]
 [6 1 4]
 [6 4 7]]

Is symmetric: True


In [11]:
import pandas as pd
df = pd.DataFrame({'Department',"IT" , "Hr"})
print(df)

            0
0  Department
1          Hr
2          IT


In [13]:
df = pd.read_csv(r"D:\University\IMT\Python Codes\employees.csv")
df

ID           Name Department  Age  Salary Joining_Date
0   1       John Doe         HR   28   50000   2020-05-21
1   2     Jane Smith         IT   34   75000   2019-06-12
2   3    Bob Johnson    Finance   45   85000   2018-07-15
3   4    Alice White         IT   29   72000   2021-01-04
4   5  Charlie Brown  Marketing   32   68000   2019-11-30
5   6      Eva Green         HR   41   54000   2017-04-22
6   7     Mike Davis    Finance   50   90000   2016-08-19
7   8   Linda Taylor         IT   26   64000   2022-02-10
8   9   James Wilson  Marketing   38   70000   2020-09-08
9  10    Sarah Adams         HR   30   55000   2021-03-18

In [15]:
print(df.head())

   ID           Name Department  Age  Salary Joining_Date
0   1       John Doe         HR   28   50000   2020-05-21
1   2     Jane Smith         IT   34   75000   2019-06-12
2   3    Bob Johnson    Finance   45   85000   2018-07-15
3   4    Alice White         IT   29   72000   2021-01-04
4   5  Charlie Brown  Marketing   32   68000   2019-11-30
